# Generated by Django 4.1.7 on 2023-03-29 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required | max-100",
                        max_length=100,
                        verbose_name="Meal name",
                    ),
                ),
                (
                    "ingerdiants",
                    models.TextField(
                        help_text="Required | max-500",
                        max_length=500,
                        verbose_name="Meal ingredients",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Required | max-500",
                        max_length=500,
                        verbose_name="Meal description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Not required  | max-5",
                        max_digits=5,
                        null=True,
                        verbose_name="Meal price",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="meals/videos/",
                        verbose_name="Meal video",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Meal owner",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="restaurant.restaurant",
                        verbose_name="Restaurant who made this meal",
                    ),
                ),
            ],
        ),
    ]
