# Generated by Django 4.1.7 on 2023-03-29 12:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="no_likes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of likes"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="meals/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "avi", "wmv", "flv", "mkv"]
                    )
                ],
                verbose_name="Meal video",
            ),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="meals.meal",
                        verbose_name="Meal Likes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Liked by",
                    ),
                ),
            ],
        ),
    ]
